[env]
CUDA_PATH = "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v13.2"
CUDA_PATH_V13_2 = "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v13.2"
CUDAToolkit_ROOT = "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v13.2"
